import jsPDF from 'jspdf';

interface DiplomaData {
  studentName: string;
  degree: string;
  field: string;
  graduationDate: string;
  issuerName: string;
  hash: string;
  verificationDate: string;
  status: 'valid' | 'invalid' | 'pending';
}

export const generateVerificationReport = (data: DiplomaData): jsPDF => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const lineHeight = 7;

  // Title
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Diploma Verification Report', pageWidth / 2, margin, { align: 'center' });

  // Date
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, margin + lineHeight * 2, { align: 'center' });

  // Status
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  const statusColor = data.status === 'valid' ? '#22c55e' : data.status === 'invalid' ? '#ef4444' : '#eab308';
  doc.setTextColor(statusColor);
  doc.text(`Status: ${data.status.toUpperCase()}`, pageWidth / 2, margin + lineHeight * 4, { align: 'center' });
  doc.setTextColor('#000000');

  // Student Information
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Student Information', margin, margin + lineHeight * 6);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  let y = margin + lineHeight * 7;
  doc.text(`Name: ${data.studentName}`, margin, y);
  y += lineHeight;
  doc.text(`Degree: ${data.degree}`, margin, y);
  y += lineHeight;
  doc.text(`Field of Study: ${data.field}`, margin, y);
  y += lineHeight;
  doc.text(`Graduation Date: ${new Date(data.graduationDate).toLocaleDateString()}`, margin, y);

  // Issuer Information
  y += lineHeight * 2;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Issuer Information', margin, y);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  y += lineHeight;
  doc.text(`Issuer: ${data.issuerName}`, margin, y);

  // Verification Details
  y += lineHeight * 2;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Verification Details', margin, y);

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  y += lineHeight;
  doc.text(`Verification Date: ${new Date(data.verificationDate).toLocaleDateString()}`, margin, y);
  y += lineHeight;
  doc.text(`Blockchain Hash: ${data.hash}`, margin, y);

  // Footer
  const footerText = 'This document was generated by the Diploma Verification Platform';
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text(footerText, pageWidth / 2, doc.internal.pageSize.getHeight() - margin, { align: 'center' });

  return doc;
}; 